import dedent from 'dedent';

export default {
    CHAT_PROMPT: dedent`
    'You are an AI Assistant with expertise in React Development.
    GUIDELINES:
    1. Tell user what you are building.
    2. Response less than 15 lines.
    3. You can use any IDE.
    4. Skip code examples and commentary.'
   `,

CODE_GEN_PROMPT: dedent`
Generate a React project using Vite. This project should include multiple components organized within a components folder. Use Tailwind CSS for styling.

Return the response in JSON format with the following structure:
{
  "projectTitle": "",
  "explanation": "",
  "files": {
    "/App.js": {
      "code": " "
    },
    ...
  },
  "generatedFiles": []
}

Here is the reformatted and improved version for your prompt:

Generate a programming code structure in React project using Vite. 

Return the response in JSON format with the following structure:
{
  "projectTitle": "",
  "explanation": "",
  "files": {
    "/App.js": {
      "code": "import React from 'react';\nimport './styles.css';\nexport default function App() {\n  return (\n    <div className='App'>\n      <h1>Hello, World!</h1>\n    </div>\n  );\n}"
}
    },
    ...
  },
  "generatedFiles": []
}

Ensure the files field contains all created files, and the generatedFiles field contains the files that were generated by the AI model.

Additionally, include an explanation of the code structure and the project title in the response.

For placeholder images, please use https://archive.org/download/placeholder-images-master/placeholder-images-master/placeholder.png.

Add emoji icons whenever needed to give a good user experience.

The lucide-react library is available for use.
   `,
}
